#!/bin/bash

# ----- Checks -----
# --- check for stow ---
if [[ ! -x /usr/bin/stow ]]; then
    echo "$(tput bold)There is no stow on the sytem! Exiting.$(tput sgr0)"
    exit 1
fi

mydir=$HOME/mydot

# --- check for mydir ( ~/mydot ) ---
if [[ ! -x $mydir ]]; then
    echo "$(tput bold)The location of the scrip is wrong! Exiting.$(tput sgr0)"
    exit 1
fi

# --- check needed directories ---
for chkdir in "$HOME/.config" "$HOME/.emacs.d" "$HOME/.themes"
do
    if [[ ! -x $chkdir ]]; then
	mkdir $chkdir
	echo "$chkdir created"
    else
	echo "$chkdir exists, good"
    fi
done

mytmp=/tmp/mytmp
mkdir $mytmp

# ----- Hide -----
for file in "$mydir/README.org" "$mydir/tree" "$mydir/Larry_Cow.png" "$mydir/stowdot"; do
    if [[ -f $file ]]; then
	mv "$file" "$mytmp/"
    fi
done

# ----- Stow or Unstow -----
if [[ "$1" = "remove" ]]; then
   # unlink
   stow -D -d $mydir * -v
   if [[ "$?" = '0' ]]; then
       echo "$(tput bold)The configuration removed successfully!$(tput sgr0)"
   fi
else
   # link
   stow -d $mydir * -v
   if [[ "$?" = '0' ]]; then
       echo "$(tput bold)The configuration transferred successfully!$(tput sgr0)"
   fi    
fi

# ----- Show -----
for file in "$mytmp/README.org" "$mytmp/tree" "$mytmp/Larry_Cow.png" "$mytmp/stowdot"; do
    if [[ -f $file ]]; then
	mv "$file" "$mydir/"
    fi
done

rm -d /tmp/mytmp
