#!/bin/sh
#
# gfetch - tiny system info for gentoo
#
# based on
# https://github.com/jschx/ufetch/
#

# INFO
# user is already defined
host="$(hostname)"
os='Gentoo Linux'
cpu="$(uname -p)"
kernel="$(uname -sr)"
uptime="$(uptime -p | sed 's/up //')"
world="$(cat /var/lib/portage/world | wc -l)"
packages="$(ls -d /var/db/pkg/*/* | wc -l)"
shell="$(basename ${SHELL})"

if [ -z "${WM}" ]; then
	if [ "${XDG_CURRENT_DESKTOP}" ]; then
		envtype='DE'
		WM="${XDG_CURRENT_DESKTOP}"
	elif [ "${DESKTOP_SESSION}" ]; then
		envtype='DE'
		WM="${DESKTOP_SESSION}"
	else
		envtype='WM'
		WM="$(tail -n 1 "${HOME}/.xinitrc" | cut -d ' ' -f 2)"
	fi
else
	envtype='WM'
fi

# Color Definitions
bold="$(tput bold)"
black="$(tput setaf 0)"
red="$(tput setaf 1)"
green="$(tput setaf 2)"
yellow="$(tput setaf 3)"
blue="$(tput setaf 4)"
magenta="$(tput setaf 5)"
cyan="$(tput setaf 6)"
white="$(tput setaf 7)"
reset="$(tput sgr0)"

# Output color
lc="${reset}${bold}${magenta}"	# labels
nc="${reset}${bold}${magenta}"	# user and hostname
ic="${reset}${bold}${white}"	# info
c0="${reset}${bold}${magenta}"	# first color
c1="${reset}${magenta}"		# second color

# OUTPUT
cat <<EOF
${c0} 	          ${nc}${USER}${ic}@${nc}${host}${reset}
${c0}     .-----.      ${lc}OS:        ${ic}${os}${reset}
${c0}   .\`    _  \`.    ${lc}CPU:       ${ic}${cpu}${reset}
${c0}   \`.   (${c1}_)   ${c0}\`.  ${lc}KERNEL:    ${ic}${kernel}${reset}
${c0}     \`${c1}.        /  ${lc}UPTIME:    ${ic}${uptime}${reset}
${c1}    .\`       .\`   ${lc}PACKAGES:  ${ic}${packages}${reset}
${c1}   /       .\`     ${lc}WORLD:     ${ic}${world}${reset}
${c1}   \____.-\`       ${lc}SHELL:     ${ic}${shell}${reset}
${c1}                  ${lc}${envtype}:        ${ic}${WM}${reset}
EOF
